In [1]:
import numpy as np

#Criando Arrays

### A partir de uma Lista Python

In [2]:
lista = [2, 4, 5, 6]
np.array(lista)

array([2, 4, 5, 6])

In [3]:
lista_2d = [[2, 4, 6], [2,8,7], [3,5,7]]
np.array(lista_2d)


array([[2, 4, 6],
       [2, 8, 7],
       [3, 5, 7]])

### Arange

In [4]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

### Zeros and Ones

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((5,5)) * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

### Linspace

In [10]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Random.rand

In [12]:
np.random.rand(2)

array([0.9292341 , 0.24800377])

In [13]:
np.random.rand(2,2)

array([[0.37658279, 0.26372433],
       [0.62447768, 0.60164738]])

### Random.randn

In [14]:
np.random.randn(5)

array([-0.47302974, -0.17438784, -0.91877292, -1.00778021, -0.93681918])

In [15]:
np.random.randn(3,2)

array([[-0.78198066, -0.53234385],
       [ 0.04098011, -0.77246685],
       [-1.46262372, -0.70846342]])

### Random.randint

In [16]:
np.random.randint(1, 100)

25

In [17]:
np.random.randint(1, 100, 5)

array([64, 56, 92, 42, 84])

# Atributos e Métodos de um array Numpy

In [18]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
rand_arr = np.random.randint(0, 50, 10)
rand_arr

array([34, 20, 39,  8, 12, 30, 10, 39, 18, 27])

### Reshape

In [20]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### min, max, argmax, argmin

In [21]:
rand_arr.max()

39

In [22]:
rand_arr.min()

8

In [23]:
rand_arr.argmax()

2

In [24]:
rand_arr.argmin()

3

### Shape

In [25]:
arr.shape

(25,)

In [26]:
rand_arr.shape

(10,)

In [27]:
rand_arr.reshape(2,5).shape

(2, 5)

### dtype

In [28]:
arr.dtype

dtype('int64')

In [29]:
rand_arr.dtype

dtype('int64')

# Indexing

In [30]:
arr = np.arange(0, 11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Breacket Indexing and Selection

In [31]:
arr[2]

2

In [32]:
arr[0:3]

array([0, 1, 2])

In [33]:
arr[0:2]

array([0, 1])

### Broadcasting

In [34]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
slice_arr = arr[0: 5]
slice_arr

array([0, 1, 2, 3, 4])

In [37]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100])

In [38]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Indexing 2D arrays (matrices)

In [39]:
arr_2d = np.array(([2, 4, 5], [3, 4, 8], [5, 9, 4]))
arr_2d

array([[2, 4, 5],
       [3, 4, 8],
       [5, 9, 4]])

In [40]:
arr_2d[2]

array([5, 9, 4])

In [41]:
arr_2d[1][2]

8

In [42]:
arr_2d[1, 2]

8

In [43]:
arr_2d[:2, 1:3]

array([[4, 5],
       [4, 8]])

### Fancy Indexing

In [44]:
arr2d = np.zeros((10,10))

arr2d_length = arr2d.shape[1]

for i in range(arr2d_length):
  arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [45]:
arr2d[[1, 6, 7]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [46]:
arr2d[[2, 4, 9], [9]]

array([2., 4., 9.])

# Selection

In [47]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [49]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

# Numpy Operations

### Aritiméticas

In [50]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [54]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [56]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Array Functions

In [57]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [58]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [59]:
np.max(arr)

10

In [60]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [61]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])